generate-types: Fix canBeOptional computation in parseSignature
A parameter can be optional if *all* of the following parameters are
optional.

This fixes several instances of “error TS1016: A required parameter
cannot follow an optional parameter” if you try to regenerate the
types for webpack with strictNullChecks enabled.

Signed-off-by: Anders Kaseorg <andersk@mit.edu>